### ISSUE TITLE
UPDATE web user interface for Wishlist microservice

### ISSUE THREAD

**Issue by sixtyferret** [CSCI-GA-2820-SU24-001/wishlists#79]

**Comment by tzuanwang** [comment]
**As a** eCommerce Manager
**I need** a UI to update existing wishlists
**So that** I can modify wishlist details
   
 ### Details and Assumptions
* Making an API request to PUT /wishlists/{wishlist_id} updates the wishlist details in the database
* The UI will include a form to enter wishlist details and a button to update the wishlist
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a eCommerce manager
When I access the homepage
Then I should see a form for entering the wishlist details
And entering the wishlist details and submitting the form by clicking the update button should update the wishlist in the database
And if the wishlist is successfully updated in the databse
Then a success message should be displayed on the UI
But if there is an error
Then a relevant error message should be displayed on the UI
```
