### ISSUE TITLE
DELETE web user interface for Wishlist microservice

### ISSUE THREAD

**Issue by sixtyferret** [CSCI-GA-2820-SU24-001/wishlists#81]

**Comment by tzuanwang** [comment]
**As a** eCommerce Manager 
**I need** a UI to delete wishlists
**So that** I can remove wishlists from the system
   
 ### Details and Assumptions
* Making an API request to PUT /wishlists/{wishlist_id}/item/{item_id} updates the wishlist item details in the database
* The UI will include a form to enter wishlist item details and wishlist ID, and a button to update the wishlist item
   
 ### Acceptance Criteria
* Making an API request to DELETE /wishlists/{wishlist_id} deletes the wishlist from the database
* The UI will include a text box to enter the wishlist ID and a button to delete the wishlist
   
 ```gherkin
Given a eCommerce manager
When I access the homepage
Then I should see a text box for entering the wishlist ID
And entering the wishlist ID and clicking the delete button should delete the wishlist from the database
And a success message should be displayed on the UI
```
